general {
    # lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    # unlock_cmd = notify-send "unlock!"      # same as above, but unlock
    #before_sleep_cmd = ~/.config/hypr/lock.sh    # lock before suspend.
    #after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

listener { #turn down monitor backlight
    timeout = 300
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}

listener { # screen off
    timeout = 600
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener { # lock
    timeout = 1800
    on-timeout = swaylock -c 000000 -ef # lock
}

listener { # suspend
    timeout = 64800
    on-timeout = loginctl hibernate
}
